### ISSUE TITLE
PMML v4.3 not supported? 

### ISSUE THREAD

**Issue by stephengaw** [openscoring/openscoring-docker#2]
When attempting to run the docker container to deploy PMML files in v4.3 using the `--net='bridge'` and `--model-dir` options, I encountered the following error:

```
...
INFO: Admin role granted to network address 172.17.0.2
May 31, 2017 11:03:44 AM org.openscoring.service.ModelResource doDeploy
SEVERE: Failed to load PMML document
java.lang.IllegalArgumentException: http://www.dmg.org/PMML-4_3
...
```
I was able to work around this for a test model by saving it as a PMML v4.2. 

Therefore, it looks like PMML 4.3 is not supported by this docker image, is this the case? If so, are there plans to support v4.3 in the future?

Thanks for all your efforts with openscoring!

**Comment by vruusmann** [comment]
This issue really belongs to the [Openscoring-Docker](https://github.com/openscoring/openscoring-docker) project.

Openscoring-Docker depends on Openscoring version 1.2.2, which was released in April 2015. I wouldn't recommend using it today.

If you want to deploy PMML 4.3 models, then you should update Openscoring dependency to some 1.3.X version. For example, replace `1.2.2` with `1.3.1` below, and redeploy:
https://github.com/openscoring/openscoring-docker/blob/master/pom.xml#L36-L40
